---
- name: Clone peervpn repo
  git:
    repo: "{{ peervpn_repo_url }}"
    dest: /app/peervpn

- name: Build peervpn
  make:
    chdir: /app/peervpn/

- name: Create dir for dpkg builder files
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: root
    group: root
  with_items:
    - "/app/peervpn_{{ peervpn_version }}_amd64/DEBIAN/"
    - "/app/peervpn_{{ peervpn_version }}_amd64/usr/local/bin/"

- name: Prepare package
  copy:
    src: "/app/peervpn/peervpn"
    dest: "/app/peervpn_{{ peervpn_version }}_amd64/usr/local/bin/"
    remote_src: yes
    mode: 755
    owner: root
    group: root

- name: Render DEBIAN/control
  template:
    src: control.j2
    dest: /app/peervpn_{{ peervpn_version }}_amd64/DEBIAN/control
    mode: 744
    owner: root
    group: root

- name: Pack peervpn into .deb
  shell:
    cmd: dpkg-deb --build --root-owner-group peervpn_{{ peervpn_version }}_amd64
    chdir: /app/
