---
- name: Clone peervpn repo
  git:
    repo: "{{ peervpn_repo_url }}"
    dest: /app/peervpn

- name: Build peervpn
  shell:
    cmd: make
    chdir: /app/peervpn/

- name: Prepare package
  shell:
    cmd: mkdir -p peervpn_{{ peervpn_version }}_amd64/usr/local/bin/ && cp /app/peervpn/peervpn peervpn_{{ peervpn_version }}_amd64/usr/local/bin/ && mkdir -p peervpn_{{ peervpn_version }}_amd64/DEBIAN
    chdir: /app/

- name: Create dir for dpkg builder files
  file:
    path: "/app/peervpn_{{ peervpn_version }}_amd64/DEBIAN/"
    state: directory

- name: Render DEBIAN/control
  template:
    src: control.j2
    dest: /app/peervpn_{{ peervpn_version }}_amd64/DEBIAN/control

- name: Pack peervpn into .deb
  shell:
    cmd: dpkg-deb --build --root-owner-group peervpn_{{ peervpn_version }}_amd64
    chdir: /app/
